<?php
/* ============================================================
 * Square API Client + Proxy
 *
 * 本ファイルは以下の役割を持ちます。
 *   1. Square Catalog / Inventory API へのリクエストを行うクライアント関数群
 *   2. ?proxy=... というクエリで呼び出すと、JSON プロキシとして動作
 *      （公開エンドポイント: 在庫数取得のみ / 管理者専用エンドポイント: カタログ・店舗一覧）
 *
 * 設定値は includes/square_config.local.php に保存します（.gitignore 対象）。
 * 鍵情報は決して JSON や JS の中に露出させません。
 * ============================================================ */

if (!defined('SQUARE_API_INTERNAL')) define('SQUARE_API_INTERNAL', true);

// ------------------------------------------------------------
// 設定ファイル読み込み（local が無ければ sample をフォールバック）
// ------------------------------------------------------------
function square_load_config(): array {
    $local  = __DIR__ . '/square_config.local.php';
    $sample = __DIR__ . '/square_config.sample.php';
    if (file_exists($local))  { $cfg = require $local;  if (is_array($cfg)) return square_normalize_config($cfg); }
    if (file_exists($sample)) { $cfg = require $sample; if (is_array($cfg)) return square_normalize_config($cfg); }
    return square_normalize_config([]);
}

function square_normalize_config(array $cfg): array {
    return [
        'application_id' => (string)($cfg['application_id'] ?? ''),
        'access_token'   => (string)($cfg['access_token']   ?? ''),
        'environment'    => ($cfg['environment'] ?? 'sandbox') === 'production' ? 'production' : 'sandbox',
        'location_ids'   => array_values(array_filter(array_map('strval', (array)($cfg['location_ids'] ?? [])))),
        'square_version' => (string)($cfg['square_version'] ?? '2024-01-18'),
    ];
}

function square_save_config(array $cfg): bool {
    $path = __DIR__ . '/square_config.local.php';
    $cfg  = square_normalize_config($cfg);
    $php  = "<?php\n// Auto-generated by admin.php. DO NOT COMMIT.\nreturn " . var_export($cfg, true) . ";\n";
    return (bool)file_put_contents($path, $php, LOCK_EX);
}

function square_api_base(string $env): string {
    return $env === 'production'
        ? 'https://connect.squareup.com/v2'
        : 'https://connect.squareupsandbox.com/v2';
}

// ------------------------------------------------------------
// 低レベル API リクエスト
// ------------------------------------------------------------
function square_request(string $method, string $endpoint, ?array $body = null, ?array $cfg = null): array {
    $cfg = $cfg ?: square_load_config();
    if ($cfg['access_token'] === '') {
        return ['__error' => 'NO_TOKEN', '__message' => 'Access Tokenが設定されていません'];
    }
    $url = square_api_base($cfg['environment']) . $endpoint;
    $ch  = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 30,
        CURLOPT_HTTPHEADER     => [
            'Square-Version: ' . $cfg['square_version'],
            'Authorization: Bearer ' . $cfg['access_token'],
            'Content-Type: application/json',
            'Accept: application/json',
        ],
    ]);
    if ($method === 'POST') {
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($body ?? new stdClass(), JSON_UNESCAPED_UNICODE));
    } elseif ($method !== 'GET') {
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $method);
        if ($body !== null) curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($body, JSON_UNESCAPED_UNICODE));
    }
    $raw  = curl_exec($ch);
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $err  = curl_error($ch);
    curl_close($ch);

    if ($err) return ['__error' => 'CURL', '__message' => $err];

    $decoded = json_decode($raw, true);
    if ($code >= 400) {
        return [
            '__error'   => 'HTTP_' . $code,
            '__message' => isset($decoded['errors'][0]['detail']) ? $decoded['errors'][0]['detail'] : ('HTTP ' . $code),
            '__details' => $decoded['errors'] ?? [],
        ];
    }
    return is_array($decoded) ? $decoded : [];
}

// ------------------------------------------------------------
// 高レベル: 店舗一覧
// ------------------------------------------------------------
function square_list_locations(?array $cfg = null): array {
    $res = square_request('GET', '/locations', null, $cfg);
    if (isset($res['__error'])) return ['error' => $res['__message'], 'locations' => []];
    $out = [];
    foreach ($res['locations'] ?? [] as $loc) {
        $out[] = [
            'id'      => $loc['id'] ?? '',
            'name'    => $loc['name'] ?? '',
            'status'  => $loc['status'] ?? '',
            'address' => isset($loc['address']) ? trim(implode(' ', array_filter([
                                $loc['address']['address_line_1'] ?? '',
                                $loc['address']['locality']       ?? '',
                                $loc['address']['country']        ?? '',
                              ]))) : '',
            'currency' => $loc['currency'] ?? '',
        ];
    }
    return ['error' => null, 'locations' => $out];
}

// ------------------------------------------------------------
// 高レベル: カタログ＋在庫（指定ロケーションの全商品とバリエーション）
// ------------------------------------------------------------
function square_list_catalog_with_inventory(string $locationId, ?array $cfg = null): array {
    $cat = square_request('GET', '/catalog/list?types=ITEM', null, $cfg);
    if (isset($cat['__error'])) return ['error' => $cat['__message'], 'items' => []];

    $items        = [];
    $variationIds = [];

    foreach ($cat['objects'] ?? [] as $item) {
        if (($item['type'] ?? '') !== 'ITEM') continue;
        $itemData = $item['item_data'] ?? [];
        // location 絞り込み: present_at_all_locations が true なら全店表示、そうでなければ list に含まれる店だけ
        $available = true;
        if (isset($item['present_at_all_locations']) && $item['present_at_all_locations'] === false) {
            $available = in_array($locationId, $item['present_at_location_ids'] ?? [], true);
        }
        if (!empty($item['absent_at_location_ids']) && in_array($locationId, $item['absent_at_location_ids'], true)) {
            $available = false;
        }
        if (!$available) continue;

        $variations = [];
        foreach ($itemData['variations'] ?? [] as $v) {
            $vd  = $v['item_variation_data'] ?? [];
            $vid = $v['id'] ?? '';
            if (!$vid) continue;
            $variationIds[] = $vid;
            $variations[] = [
                'variation_id'   => $vid,
                'variation_name' => $vd['name'] ?? 'Regular',
                'sku'            => $vd['sku'] ?? '',
                'price'          => isset($vd['price_money']) ? (int)($vd['price_money']['amount'] ?? 0) : null,
                'currency'       => $vd['price_money']['currency'] ?? '',
                'quantity'       => 0,
                'track_inventory'=> !empty($vd['track_inventory']),
            ];
        }
        $items[] = [
            'item_id'    => $item['id'] ?? '',
            'item_name'  => $itemData['name'] ?? '(名称不明)',
            'category'   => $itemData['category_id'] ?? '',
            'variations' => $variations,
        ];
    }

    // 在庫を一括取得
    if ($variationIds) {
        // batch-retrieve は最大1000件まで、念のため chunk
        $chunks = array_chunk(array_unique($variationIds), 500);
        $countMap = [];
        foreach ($chunks as $chunk) {
            $inv = square_request('POST', '/inventory/counts/batch-retrieve', [
                'catalog_object_ids' => array_values($chunk),
                'location_ids'       => [$locationId],
            ], $cfg);
            if (isset($inv['__error'])) continue;
            foreach ($inv['counts'] ?? [] as $c) {
                if (($c['state'] ?? '') === 'IN_STOCK') {
                    $countMap[$c['catalog_object_id']] = (float)($c['quantity'] ?? 0);
                }
            }
        }
        foreach ($items as &$it) {
            foreach ($it['variations'] as &$vv) {
                if (isset($countMap[$vv['variation_id']])) {
                    $vv['quantity'] = $countMap[$vv['variation_id']];
                }
            }
            unset($vv);
        }
        unset($it);
    }

    return ['error' => null, 'items' => $items, 'fetched_at' => date('c')];
}

// ------------------------------------------------------------
// 高レベル: 指定 variationId 群 × locationId 群 の在庫マップ
// 戻り値: [ "locationId|variationId" => quantity, ... ]
// ------------------------------------------------------------
function square_fetch_inventory_map(array $variationIds, array $locationIds, ?array $cfg = null): array {
    $variationIds = array_values(array_unique(array_filter($variationIds)));
    $locationIds  = array_values(array_unique(array_filter($locationIds)));
    if (!$variationIds || !$locationIds) return ['error' => null, 'map' => new stdClass(), 'fetched_at' => date('c')];

    $map = [];
    $chunks = array_chunk($variationIds, 500);
    foreach ($chunks as $chunk) {
        $inv = square_request('POST', '/inventory/counts/batch-retrieve', [
            'catalog_object_ids' => $chunk,
            'location_ids'       => $locationIds,
        ], $cfg);
        if (isset($inv['__error'])) {
            return ['error' => $inv['__message'], 'map' => new stdClass()];
        }
        foreach ($inv['counts'] ?? [] as $c) {
            $key = ($c['location_id'] ?? '') . '|' . ($c['catalog_object_id'] ?? '');
            if (($c['state'] ?? '') === 'IN_STOCK') {
                $map[$key] = (float)($c['quantity'] ?? 0);
            }
        }
    }
    return ['error' => null, 'map' => $map, 'fetched_at' => date('c')];
}

// ------------------------------------------------------------
// 公開プロキシ: JSON ファイル（cafe_menu / goods）に紐づく在庫数だけを返す
// 鍵はサーバ側にのみ存在し、フロントには渡らない。
// ------------------------------------------------------------
function square_public_inventory_for_dataset(string $datasetKey): array {
    $allowed = ['cafe_menu' => 'cafe_menu.json', 'goods' => 'goods.json'];
    if (!isset($allowed[$datasetKey])) return ['error' => 'unknown dataset', 'map' => new stdClass()];

    $path = dirname(__DIR__) . '/assets/data/' . $allowed[$datasetKey];
    if (!file_exists($path)) return ['error' => null, 'map' => new stdClass()];

    $items = json_decode((string)file_get_contents($path), true);
    if (!is_array($items)) return ['error' => null, 'map' => new stdClass()];

    $pairs = [];
    foreach ($items as $item) {
        if (!empty($item['variations']) && is_array($item['variations'])) {
            foreach ($item['variations'] as $v) {
                if (!empty($v['variationId']) && !empty($v['locationId'])) {
                    $pairs[] = [$v['variationId'], $v['locationId']];
                }
            }
        } else {
            if (!empty($item['variationId']) && !empty($item['locationId'])) {
                $pairs[] = [$item['variationId'], $item['locationId']];
            }
        }
    }
    if (!$pairs) return ['error' => null, 'map' => new stdClass(), 'fetched_at' => date('c')];

    $variationIds = array_unique(array_column($pairs, 0));
    $locationIds  = array_unique(array_column($pairs, 1));
    return square_fetch_inventory_map($variationIds, $locationIds);
}

// ============================================================
// ?proxy=... モード（このファイル単体での呼び出し）
// ============================================================
if (basename($_SERVER['SCRIPT_FILENAME'] ?? '') === basename(__FILE__) && isset($_GET['proxy'])) {
    header('Content-Type: application/json; charset=utf-8');
    header('Cache-Control: no-store, max-age=0');

    $proxy = $_GET['proxy'];

    // ---- 公開エンドポイント: 在庫数のみ ----
    if ($proxy === 'inventory') {
        $key = $_GET['dataset'] ?? '';
        echo json_encode(square_public_inventory_for_dataset($key), JSON_UNESCAPED_UNICODE);
        exit;
    }

    // ---- ここから先は管理者専用 ----
    session_start();
    if (empty($_SESSION['admin_auth'])) {
        http_response_code(401);
        echo json_encode(['error' => 'unauthorized']);
        exit;
    }

    if ($proxy === 'locations') {
        echo json_encode(square_list_locations(), JSON_UNESCAPED_UNICODE);
        exit;
    }
    if ($proxy === 'catalog') {
        $locId = $_GET['location_id'] ?? '';
        if ($locId === '') { echo json_encode(['error' => 'location_id required', 'items' => []]); exit; }
        echo json_encode(square_list_catalog_with_inventory($locId), JSON_UNESCAPED_UNICODE);
        exit;
    }
    if ($proxy === 'config') {
        // 設定値の取得（access_token はマスクして返す）
        $cfg = square_load_config();
        $masked = $cfg;
        if ($masked['access_token']) {
            $t = $masked['access_token'];
            $masked['access_token_masked'] = strlen($t) > 8 ? substr($t, 0, 4) . '••••' . substr($t, -4) : '••••';
            $masked['access_token_set']    = true;
        } else {
            $masked['access_token_masked'] = '';
            $masked['access_token_set']    = false;
        }
        unset($masked['access_token']); // 生のトークンは絶対に返さない
        echo json_encode($masked, JSON_UNESCAPED_UNICODE);
        exit;
    }

    http_response_code(400);
    echo json_encode(['error' => 'unknown proxy']);
    exit;
}
